import React from 'react'

const Footer = () => {
  return (
    <footer className='shadow-2xl py-8'>
        <p className="text-lg font-bold text-center text-green-600 sm:text-xl md:text-2xl">Yulduzli bolalar ©2025 year | Regenerated by Ismoilov</p>
    </footer>
  )
}

export default Footer